In [146]:
# Dependencies and Setup

import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

In [147]:
# Store csv created in part one into a DataFrame
vac_data_df = pd.read_csv("VacationspotsUSA.csv")
vac_data_df

,Places,Lat,Long,crime rate for county violent,US average (violent),Crime rate for county property,US average property,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,"Grand Canyon National Park, Arizona",36.089408,-113.964375,30.0,22.7,52.1,35.4,NaN,NaN,NaN
1,Yosemite National Park,37.453519,-119.831300,27.3,NaN,56.2,NaN,NaN,NaN,NaN
2,Yellowstone National Park,44.416229,-110.733863,12.9,NaN,24.6,NaN,NaN,NaN,NaN
3,"Maui, Hawaii",20.803410,-156.618180,9.0,NaN,26.6,NaN,NaN,NaN,NaN
4,"Glacier National Park, Montana",48.659697,-114.406285,26.9,NaN,22.7,NaN,NaN,NaN,NaN
5,New York City,40.757979,-73.987731,28.2,NaN,24.9,NaN,NaN,NaN,NaN
6,"San Francisco, CA",37.808843,-122.534296,39.6,NaN,79.2,NaN,NaN,NaN,NaN
7,Washington D.C.,38.892981,-77.016242,56.2,NaN,63.9,NaN,NaN,NaN,NaN
8,"Honolulu, HI",21.275721,-157.829615,17.4,NaN,43.4,NaN,NaN,NaN,NaN
9,"Telluride, CO",37.911853,-107.869520,12.2,NaN,44.7,NaN,NaN,NaN,NaN
10,"Jackson Hole, WY",43.596593,-110.864944,17.2,NaN,24.1,NaN,NaN,NaN,NaN
11,Lake Tahoe,39.092718,-120.185053,34.3,NaN,27.3,NaN,NaN,NaN,NaN
12,"Juneu, Alaska",58.380128,-135.318701,37.9,NaN,55.6,NaN,NaN,NaN,NaN
13,Grand Teton National Park,43.750794,-110.968699,17.2,NaN,24.1,NaN,NaN,NaN,NaN
14,Zion National Park,37.322010,-113.159775,10.6,NaN,25.8,NaN,NaN,NaN,NaN
15,"Kauai, HI",22.071484,-159.663866,8.5,NaN,24.9,NaN,NaN,NaN,NaN
16,"San Diego, CA",32.713688,-117.176329,24.4,NaN,31.4,NaN,NaN,NaN,NaN
17,"Aspen, CO",39.200922,-106.877860,7.6,NaN,62.5,NaN,NaN,NaN,NaN
18,"New Orleans, LA",29.957448,-90.065133,49.1,NaN,56.8,NaN,NaN,NaN,NaN
19,"Boston, MA",42.337637,-70.993040,37.3,NaN,35.8,NaN,NaN,NaN,NaN
20,"Chicago, IL",41.882552,-87.624740,49.9,NaN,46.3,NaN,NaN,NaN,NaN
21,"Seattle, WA",47.612943,-122.482148,32.3,NaN,76.9,NaN,NaN,NaN,NaN
22,"Sedona, AZ",34.854373,-111.830158,13.8,NaN,27.7,NaN,NaN,NaN,NaN
23,"Miami, FL",25.782391,-80.299499,48.8,NaN,62.7,NaN,NaN,NaN,NaN
24,"Outer Banks, Kinnakeet, NC",35.533790,-75.775978,17.9,NaN,62.0,NaN,NaN,NaN,NaN
25,"Las Vegas, NV",36.117489,-115.201462,40.9,NaN,43.4,NaN,NaN,NaN,NaN
26,Charleston SC,32.820967,-80.110563,17.7,NaN,35.9,NaN,NaN,NaN,NaN
27,"Key West, FL",24.564635,-81.815648,24.7,NaN,62.5,NaN,NaN,NaN,NaN
28,Lake Placid,43.966053,-75.677348,11.8,NaN,23.9,NaN,NaN,NaN,NaN
29,"Savannah, GA",32.038767,-81.340364,22.2,NaN,51.5,NaN,NaN,NaN,NaN

In [148]:
# Configure gmaps
gmaps.configure(api_key=g_key)

In [149]:
dest_df = vac_data_df[["Places", "Lat", "Long", "crime rate for county violent", "US average (violent)","Crime rate for county property","US average property"]].copy()
dest_df ["#restaurants"]= ""
dest_df ["ave_rest_rating"] =""
dest_df ["#attractions"]=""
dest_df ["ave_attraction_rating"]=""
dest_df ["icon"]=""
dest_df

,Places,Lat,Long,crime rate for county violent,US average (violent),Crime rate for county property,US average property,#restaurants,ave_rest_rating,#attractions,ave_attraction_rating,icon
0,"Grand Canyon National Park, Arizona",36.089408,-113.964375,30.0,22.7,52.1,35.4,,,,,
1,Yosemite National Park,37.453519,-119.831300,27.3,NaN,56.2,NaN,,,,,
2,Yellowstone National Park,44.416229,-110.733863,12.9,NaN,24.6,NaN,,,,,
3,"Maui, Hawaii",20.803410,-156.618180,9.0,NaN,26.6,NaN,,,,,
4,"Glacier National Park, Montana",48.659697,-114.406285,26.9,NaN,22.7,NaN,,,,,
5,New York City,40.757979,-73.987731,28.2,NaN,24.9,NaN,,,,,
6,"San Francisco, CA",37.808843,-122.534296,39.6,NaN,79.2,NaN,,,,,
7,Washington D.C.,38.892981,-77.016242,56.2,NaN,63.9,NaN,,,,,
8,"Honolulu, HI",21.275721,-157.829615,17.4,NaN,43.4,NaN,,,,,
9,"Telluride, CO",37.911853,-107.869520,12.2,NaN,44.7,NaN,,,,,
10,"Jackson Hole, WY",43.596593,-110.864944,17.2,NaN,24.1,NaN,,,,,
11,Lake Tahoe,39.092718,-120.185053,34.3,NaN,27.3,NaN,,,,,
12,"Juneu, Alaska",58.380128,-135.318701,37.9,NaN,55.6,NaN,,,,,
13,Grand Teton National Park,43.750794,-110.968699,17.2,NaN,24.1,NaN,,,,,
14,Zion National Park,37.322010,-113.159775,10.6,NaN,25.8,NaN,,,,,
15,"Kauai, HI",22.071484,-159.663866,8.5,NaN,24.9,NaN,,,,,
16,"San Diego, CA",32.713688,-117.176329,24.4,NaN,31.4,NaN,,,,,
17,"Aspen, CO",39.200922,-106.877860,7.6,NaN,62.5,NaN,,,,,
18,"New Orleans, LA",29.957448,-90.065133,49.1,NaN,56.8,NaN,,,,,
19,"Boston, MA",42.337637,-70.993040,37.3,NaN,35.8,NaN,,,,,
20,"Chicago, IL",41.882552,-87.624740,49.9,NaN,46.3,NaN,,,,,
21,"Seattle, WA",47.612943,-122.482148,32.3,NaN,76.9,NaN,,,,,
22,"Sedona, AZ",34.854373,-111.830158,13.8,NaN,27.7,NaN,,,,,
23,"Miami, FL",25.782391,-80.299499,48.8,NaN,62.7,NaN,,,,,
24,"Outer Banks, Kinnakeet, NC",35.533790,-75.775978,17.9,NaN,62.0,NaN,,,,,
25,"Las Vegas, NV",36.117489,-115.201462,40.9,NaN,43.4,NaN,,,,,
26,Charleston SC,32.820967,-80.110563,17.7,NaN,35.9,NaN,,,,,
27,"Key West, FL",24.564635,-81.815648,24.7,NaN,62.5,NaN,,,,,
28,Lake Placid,43.966053,-75.677348,11.8,NaN,23.9,NaN,,,,,
29,"Savannah, GA",32.038767,-81.340364,22.2,NaN,51.5,NaN,,,,,

In [150]:
# Find Place ID
params = {
    "key": g_key,
    "inputtype": "textquery",
    "fields": "icon"
}

# Iterate through 
for index, row in dest_df.iterrows():
    # get place from df
    places = row["Places"]
   
    params["input"] = f"{places}"
    
    # Use the search term for each place

    base_url = "https://maps.googleapis.com/maps/api/place/findplacefromtext/json"

    # make request and print url
    response = requests.get(base_url, params=params)
    
    # convert to json
    place_ids = response.json()
    
    # Grab the place id from the results and store the name
    dest_df.loc[index, "icon"] = place_ids["candidates"][0]["icon"]
  
dest_df

,Places,Lat,Long,crime rate for county violent,US average (violent),Crime rate for county property,US average property,#restaurants,ave_rest_rating,#attractions,ave_attraction_rating,icon
0,"Grand Canyon National Park, Arizona",36.089408,-113.964375,30.0,22.7,52.1,35.4,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
1,Yosemite National Park,37.453519,-119.831300,27.3,NaN,56.2,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
2,Yellowstone National Park,44.416229,-110.733863,12.9,NaN,24.6,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
3,"Maui, Hawaii",20.803410,-156.618180,9.0,NaN,26.6,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
4,"Glacier National Park, Montana",48.659697,-114.406285,26.9,NaN,22.7,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
5,New York City,40.757979,-73.987731,28.2,NaN,24.9,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
6,"San Francisco, CA",37.808843,-122.534296,39.6,NaN,79.2,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
7,Washington D.C.,38.892981,-77.016242,56.2,NaN,63.9,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
8,"Honolulu, HI",21.275721,-157.829615,17.4,NaN,43.4,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
9,"Telluride, CO",37.911853,-107.869520,12.2,NaN,44.7,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
10,"Jackson Hole, WY",43.596593,-110.864944,17.2,NaN,24.1,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
11,Lake Tahoe,39.092718,-120.185053,34.3,NaN,27.3,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
12,"Juneu, Alaska",58.380128,-135.318701,37.9,NaN,55.6,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
13,Grand Teton National Park,43.750794,-110.968699,17.2,NaN,24.1,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
14,Zion National Park,37.322010,-113.159775,10.6,NaN,25.8,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
15,"Kauai, HI",22.071484,-159.663866,8.5,NaN,24.9,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
16,"San Diego, CA",32.713688,-117.176329,24.4,NaN,31.4,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
17,"Aspen, CO",39.200922,-106.877860,7.6,NaN,62.5,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
18,"New Orleans, LA",29.957448,-90.065133,49.1,NaN,56.8,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
19,"Boston, MA",42.337637,-70.993040,37.3,NaN,35.8,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
20,"Chicago, IL",41.882552,-87.624740,49.9,NaN,46.3,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
21,"Seattle, WA",47.612943,-122.482148,32.3,NaN,76.9,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
22,"Sedona, AZ",34.854373,-111.830158,13.8,NaN,27.7,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
23,"Miami, FL",25.782391,-80.299499,48.8,NaN,62.7,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
24,"Outer Banks, Kinnakeet, NC",35.533790,-75.775978,17.9,NaN,62.0,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
25,"Las Vegas, NV",36.117489,-115.201462,40.9,NaN,43.4,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
26,Charleston SC,32.820967,-80.110563,17.7,NaN,35.9,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
27,"Key West, FL",24.564635,-81.815648,24.7,NaN,62.5,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
28,Lake Placid,43.966053,-75.677348,11.8,NaN,23.9,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...
29,"Savannah, GA",32.038767,-81.340364,22.2,NaN,51.5,NaN,,,,,https://maps.gstatic.com/mapfiles/place_api/ic...

In [151]:
# Set parameters to search for tourist attractions
params = {
    "radius": 50000,
    "type": "tourist_attraction",
    "key": g_key
}

# Iterate through 
for index, row in dest_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Long"]
    
    params["location"] = f"{lat},{lng}"
    
    # Use the search term: "tourist_attraction" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    attraction = requests.get(base_url, params=params)
    
    # convert to json
    attractions = attraction.json()
    
    count=0
    
    for x in attractions["results"]:
        if x["name"]:
            count+=1
    #print(count)
    dest_df.loc[index, "#attractions"] = count
    
    
    ratings=[]
    
    for x in attractions["results"]:
        #pprint(x)
        try:
            ratings.append(x["rating"])
        except:
            print("N/A")
    #print(ratings)
    attr=np.mean(ratings)
    
    dest_df.loc[index, "ave_attraction_rating"] = np.around([attr], decimals=1)

dest_df

N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A

,Places,Lat,Long,crime rate for county violent,US average (violent),Crime rate for county property,US average property,#restaurants,ave_rest_rating,#attractions,ave_attraction_rating,icon
0,"Grand Canyon National Park, Arizona",36.089408,-113.964375,30.0,22.7,52.1,35.4,,,9,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
1,Yosemite National Park,37.453519,-119.831300,27.3,NaN,56.2,NaN,,,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
2,Yellowstone National Park,44.416229,-110.733863,12.9,NaN,24.6,NaN,,,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
3,"Maui, Hawaii",20.803410,-156.618180,9.0,NaN,26.6,NaN,,,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
4,"Glacier National Park, Montana",48.659697,-114.406285,26.9,NaN,22.7,NaN,,,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
5,New York City,40.757979,-73.987731,28.2,NaN,24.9,NaN,,,20,4.5,https://maps.gstatic.com/mapfiles/place_api/ic...
6,"San Francisco, CA",37.808843,-122.534296,39.6,NaN,79.2,NaN,,,20,4.5,https://maps.gstatic.com/mapfiles/place_api/ic...
7,Washington D.C.,38.892981,-77.016242,56.2,NaN,63.9,NaN,,,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
8,"Honolulu, HI",21.275721,-157.829615,17.4,NaN,43.4,NaN,,,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
9,"Telluride, CO",37.911853,-107.869520,12.2,NaN,44.7,NaN,,,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
10,"Jackson Hole, WY",43.596593,-110.864944,17.2,NaN,24.1,NaN,,,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
11,Lake Tahoe,39.092718,-120.185053,34.3,NaN,27.3,NaN,,,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
12,"Juneu, Alaska",58.380128,-135.318701,37.9,NaN,55.6,NaN,,,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
13,Grand Teton National Park,43.750794,-110.968699,17.2,NaN,24.1,NaN,,,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
14,Zion National Park,37.322010,-113.159775,10.6,NaN,25.8,NaN,,,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
15,"Kauai, HI",22.071484,-159.663866,8.5,NaN,24.9,NaN,,,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
16,"San Diego, CA",32.713688,-117.176329,24.4,NaN,31.4,NaN,,,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
17,"Aspen, CO",39.200922,-106.877860,7.6,NaN,62.5,NaN,,,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
18,"New Orleans, LA",29.957448,-90.065133,49.1,NaN,56.8,NaN,,,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
19,"Boston, MA",42.337637,-70.993040,37.3,NaN,35.8,NaN,,,20,4.5,https://maps.gstatic.com/mapfiles/place_api/ic...
20,"Chicago, IL",41.882552,-87.624740,49.9,NaN,46.3,NaN,,,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
21,"Seattle, WA",47.612943,-122.482148,32.3,NaN,76.9,NaN,,,20,4.5,https://maps.gstatic.com/mapfiles/place_api/ic...
22,"Sedona, AZ",34.854373,-111.830158,13.8,NaN,27.7,NaN,,,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
23,"Miami, FL",25.782391,-80.299499,48.8,NaN,62.7,NaN,,,20,4.4,https://maps.gstatic.com/mapfiles/place_api/ic...
24,"Outer Banks, Kinnakeet, NC",35.533790,-75.775978,17.9,NaN,62.0,NaN,,,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
25,"Las Vegas, NV",36.117489,-115.201462,40.9,NaN,43.4,NaN,,,20,4.4,https://maps.gstatic.com/mapfiles/place_api/ic...
26,Charleston SC,32.820967,-80.110563,17.7,NaN,35.9,NaN,,,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
27,"Key West, FL",24.564635,-81.815648,24.7,NaN,62.5,NaN,,,20,4.5,https://maps.gstatic.com/mapfiles/place_api/ic...
28,Lake Placid,43.966053,-75.677348,11.8,NaN,23.9,NaN,,,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
29,"Savannah, GA",32.038767,-81.340364,22.2,NaN,51.5,NaN,,,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...

In [152]:
# Set parameters to search for tourist attractions
params = {
    "radius": 50000,
    "type": "restaurant",
    "key": g_key
}

# Iterate through 
for index, row in dest_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Long"]
    
    params["location"] = f"{lat},{lng}"
    
    # Use the search term: "tourist_attraction" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    restaurant = requests.get(base_url, params=params)
    
    # convert to json
    restaurants = restaurant.json()
    
    count=0
    
    for x in restaurants["results"]:
        if x["name"]:
            count+=1
    #print(count)
    dest_df.loc[index, "#restaurants"] = count
    
    
    ratings=[]
    
    for x in restaurants["results"]:
        #pprint(x)
        try:
            ratings.append(x["rating"])
        except:
            print("N/A")
    #print(ratings)
    rate=np.mean(ratings)
    
    dest_df.loc[index,"ave_rest_rating"] = np.around([rate], decimals=1)

dest_df

N/A
N/A
N/A
N/A
N/A

,Places,Lat,Long,crime rate for county violent,US average (violent),Crime rate for county property,US average property,#restaurants,ave_rest_rating,#attractions,ave_attraction_rating,icon
0,"Grand Canyon National Park, Arizona",36.089408,-113.964375,30.0,22.7,52.1,35.4,6,4,9,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
1,Yosemite National Park,37.453519,-119.831300,27.3,NaN,56.2,NaN,20,4.3,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
2,Yellowstone National Park,44.416229,-110.733863,12.9,NaN,24.6,NaN,20,3.7,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
3,"Maui, Hawaii",20.803410,-156.618180,9.0,NaN,26.6,NaN,20,4.3,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
4,"Glacier National Park, Montana",48.659697,-114.406285,26.9,NaN,22.7,NaN,20,4.3,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
5,New York City,40.757979,-73.987731,28.2,NaN,24.9,NaN,20,4.3,20,4.5,https://maps.gstatic.com/mapfiles/place_api/ic...
6,"San Francisco, CA",37.808843,-122.534296,39.6,NaN,79.2,NaN,20,4.3,20,4.5,https://maps.gstatic.com/mapfiles/place_api/ic...
7,Washington D.C.,38.892981,-77.016242,56.2,NaN,63.9,NaN,20,4.3,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
8,"Honolulu, HI",21.275721,-157.829615,17.4,NaN,43.4,NaN,20,4.3,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
9,"Telluride, CO",37.911853,-107.869520,12.2,NaN,44.7,NaN,20,4.3,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
10,"Jackson Hole, WY",43.596593,-110.864944,17.2,NaN,24.1,NaN,20,4.3,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
11,Lake Tahoe,39.092718,-120.185053,34.3,NaN,27.3,NaN,20,4.1,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
12,"Juneu, Alaska",58.380128,-135.318701,37.9,NaN,55.6,NaN,20,4.2,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
13,Grand Teton National Park,43.750794,-110.968699,17.2,NaN,24.1,NaN,20,4.3,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
14,Zion National Park,37.322010,-113.159775,10.6,NaN,25.8,NaN,20,4,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
15,"Kauai, HI",22.071484,-159.663866,8.5,NaN,24.9,NaN,20,4.3,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
16,"San Diego, CA",32.713688,-117.176329,24.4,NaN,31.4,NaN,20,4.4,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
17,"Aspen, CO",39.200922,-106.877860,7.6,NaN,62.5,NaN,20,4.3,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
18,"New Orleans, LA",29.957448,-90.065133,49.1,NaN,56.8,NaN,20,4.5,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
19,"Boston, MA",42.337637,-70.993040,37.3,NaN,35.8,NaN,20,4.4,20,4.5,https://maps.gstatic.com/mapfiles/place_api/ic...
20,"Chicago, IL",41.882552,-87.624740,49.9,NaN,46.3,NaN,20,4.4,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
21,"Seattle, WA",47.612943,-122.482148,32.3,NaN,76.9,NaN,20,4.3,20,4.5,https://maps.gstatic.com/mapfiles/place_api/ic...
22,"Sedona, AZ",34.854373,-111.830158,13.8,NaN,27.7,NaN,20,4.2,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
23,"Miami, FL",25.782391,-80.299499,48.8,NaN,62.7,NaN,20,4.2,20,4.4,https://maps.gstatic.com/mapfiles/place_api/ic...
24,"Outer Banks, Kinnakeet, NC",35.533790,-75.775978,17.9,NaN,62.0,NaN,20,4.3,20,4.7,https://maps.gstatic.com/mapfiles/place_api/ic...
25,"Las Vegas, NV",36.117489,-115.201462,40.9,NaN,43.4,NaN,20,4.2,20,4.4,https://maps.gstatic.com/mapfiles/place_api/ic...
26,Charleston SC,32.820967,-80.110563,17.7,NaN,35.9,NaN,20,4.5,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
27,"Key West, FL",24.564635,-81.815648,24.7,NaN,62.5,NaN,20,4.3,20,4.5,https://maps.gstatic.com/mapfiles/place_api/ic...
28,Lake Placid,43.966053,-75.677348,11.8,NaN,23.9,NaN,20,4.2,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...
29,"Savannah, GA",32.038767,-81.340364,22.2,NaN,51.5,NaN,20,4.2,20,4.6,https://maps.gstatic.com/mapfiles/place_api/ic...

In [154]:
dest_df.to_csv("output.csv", index=False, header=True)